1911-team-two/grace-shopper

package-lock.json, package.json, server/db/models/products.js, server/db/models/user.js
---
Added model definitions for products and refined the existing for users
=> feature: added the users and products models

client/components/Home.js, client/components/SingleProduct.js, client/components/index.js, client/components/navbar.js, client/components/temp_style.css, client/routes.js
---
This adds placeholder Home/All Products and Single Product components as well as corresponding routes.
=> Frontend components #6

script/seed.js, server/api/index.js, server/api/products.js, server/api/products.spec.js, server/api/users.js, server/api/users.spec.js, server/db/models/index.js, server/db/models/user.js
---
_Your PR Notes Here_
I ran into some issues when running npm start-dev, apparently we were using older Sequelize documentation. The type Sequelize.NUMBER is old and doesn't work so changed it to Sequelize.INTEGER, this resolved the error. 
Additionally I added routes to get all the users and all the products as well as a single user and single product and basic test cases.
=> added get routes for products and users

client/store/products.js, tests/redux.spec.js
---
Wrote portion of Redux store to fetch product data from API + tests.
=> wrote tests for retrieving products to store #8

client/components/AllProducts.js, client/components/Home.js, client/routes.js, client/store/index.js, client/store/products.js, package-lock.json, package.json, tests/AllProducts.spec.js, tests/Home.spec.js, tests/setup/setupEnzyme.js
---
Added fetching all products from home page. Added tests (but still seeking the best way to write these)
=> All products data #15

script/seed.js, server/db/models/addressBook.js, server/db/models/cart.js, server/db/models/index.js, server/db/models/order.js, server/db/models/products.js, server/db/models/user.js, tests/product.spec.js, tests/user.spec.js
This is the db schema we all went over this morning
Successfully made associations between tables 
What's left to do:
=> Fix: dB schema complete

script/seed.js
Here's our final product data: 
Please note - I got a weird error when I tried to seed to db. I commented out all the products in the products array, and uncommented them one at a time as I seeded. It worked that way.
=> Fix: completed the data for the product table

.travis.yml, server/auth/google.js, server/index.js
---
_Your PR Notes Here_
Passwords are already hashed in the user model, important data (like passwords and salt) are omitted from being sent in the response, all the secrets like process.env.DATABASE_URL, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET etc... are stored in the secrets.js file.  It is required before the other stuffs load so I moved it. Since we are not committing this file for security reasons, it's inside .gitignore... So we all need to set this secrets file separately.
=> rudiments of security

client/components/SingleProduct.js, client/components/cart.js, client/routes.js, client/store/cart.js, server/api/cart.js, server/api/index.js
Cart was moved from Redux store to sessions to avoid deleting cart on refresh/otherwise leaving the website. Added API routes to allow Axios calls from front end to back end for cart operations.
=> Implement sessions #44

client/components/cart.js, client/components/cartitem.js, client/store/cart.js, server/api/cart.js
Added additional functionality to cart to enable removing from cart and editing item quantity and persisting these changes in sessions.
=> Cart operations #47

client/components/Checkout.js, client/store/order.js, server/api/index.js, server/api/order.js, server/db/models/user.js
---
Created a route for posting a new order. Created a handleSubmit that initiates posting the order.
=> Checkout submission #42

client/app.js, client/components/SingleProduct.js
Fixed bug where single product view wouldn't load a product if the URL is typed directly into the address bar.
=> fixed single product bug

client/components/SingleOrder.js, client/components/index.js, client/routes.js, client/store/order.js, server/api/order.js
Here is the single order view
Still need to make the link between the order history page and the single order render
Still need to add tests for this new feature
=> Order history single

script/seed.js, server/db/models/cart.js, server/db/models/user.js
Checked associations 
Deleted the allowNull requirement for isAdmin 
Seeded another user to the db that is an Admin for further testing
=> Finalizing db

client/store/order.js
=> fixed user profile bug

client/components/SingleOrder.js, client/components/UserProfile.js, client/store/order.js
This change does the following: 
- there was a route error in redux that kept this from rendering - fixed
- formats the date/time to a more normal formatting 
- fixes the appearance of prices 
- adds the overall total on the single order rendering 
- links overall order view to single order view
=> fixed: user profile order history and single order rendering

client/components/Cart.js, client/components/Checkout.js, client/components/OrderConfirmation.js, client/components/index.js, client/routes.js, client/store/order.js, tests/models.spec.js
Added an order confirmation page after submitting at checkout. It automatically redirects upon submission and shows the user the order number. If a user tries to access the route without being redirected from checkout, it redirects them to the home page.
=> Implemented order confirmation page

client/components/Cart.js, client/components/CartItem.js, client/components/SingleOrder.js, client/components/SingleProduct.js, client/components/Thumbnail.js, client/components/UserProfile.js, script/seed.js, script/seed.js.rej, server/db/models/products.js, server/db/models/products.js.rej, tests/models.spec.js
Added alternative views of the product to the db and those changes are reflected in the front-end rendering on allProducts, singleProducts, cart, profile, etc
=> Db seed revise

client/components/SingleProduct.js
=> Feature: css for single product view

client/components/SingleOrder.js, client/components/UserProfile.js
#20 # Assignee Tasks
CSS added for profile order history, single order history
=> Feature: css added for profile, order history, and single order

client/components/SingleProduct.js, client/routes.js, webpack.config.js
=> Cart modal #88

client/components/Checkout.js
---
Added one req for complete order button to activate
Button functionality fixed 
Button css added
=> Checkout form revise

client/components/Checkout.js, client/store/cart.js, server/api/cart.js
=> Clear cart on checkout #95

client/app.js, client/components/CartModal.js, client/components/Checkout.js, client/components/Navbar.js, client/components/SingleProduct.js, client/store/index.js, client/utils/GlobalStyles.js
=> New cart modal

client/components/AllProducts.js, client/components/AuthForm.js, client/components/Checkout.js, client/components/FeaturedProducts.js, client/components/Navbar.js, client/components/Thumbnail.js, client/store/products.js, client/store/user.js
Fixed bug where all products wasn't displaying featured products as well. Updated cart to reflect quantity, rather than unique items.
=> All Products bug fix
